Repository KendallDoesCoding/backward-text, pull requests merged in 2023-03, with the labels that each got.

#22 updated the font and made other css changes
  index.html
  styles.css
Labels: size/S

#23 design updated
  index.html
  styles.css
Labels: size/L

#26 Change text color of buttion(CSS)
  index.html
  styles.css
Labels: size/XS
